version: '3.8'

services:
  portfolio:
    image: mrstjch/portfolio:v2.0
    expose:
      - 9000
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20M'
    restart: unless-stopped

networks:
  nginx:
    external: true
